<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <PackageId>Toggle.Net.Autofac</PackageId>
        <Authors>Roger Kratz</Authors>
        <Description>Feature flags for .net</Description>
        <PackageProjectUrl>https://github.com/Teleopti/Toggle.Net</PackageProjectUrl>
        <PackageLicenseUrl>http://opensource.org/licenses/MIT</PackageLicenseUrl>
        <PackageTags>flag, toggle, bit, config, feature, branch</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageVersion>2.3.0$(GITHUB_RUN_NUMBER)</PackageVersion>
        <Version>2.3.0$(GITHUB_RUN_NUMBER)</Version>

        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Autofac" Version="7.1.0" />
        <PackageReference Include="LinFu.DynamicProxy" Version="2.1.2" />
    </ItemGroup>
</Project>